spring:
  thymeleaf:
    cache: true

server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework

backend:
  admin-api:
    base-url: ${BACKEND_ADMIN_API_BASE_URL:https://api.hsft.io.kr}
    internal-key: ${INTERNAL_API_KEY:local-admin-web-key}
